---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infra-homecluster-dev-v1alpha1-node
  failurePolicy: Fail
  name: vnode-v1alpha1.kb.io
  rules:
  - apiGroups:
    - infra.homecluster.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
