# This rule is not used by the project homelab-autoscaler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to infra.homecluster.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: homelab-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: group-viewer-role
rules:
- apiGroups:
  - infra.homecluster.dev
  resources:
  - groups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.homecluster.dev
  resources:
  - groups/status
  verbs:
  - get
