apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
    labels:
      kubernetesNodeName: worker-node-1
  - role: worker
    labels:
      kubernetesNodeName: worker-node-2
  - role: worker
    labels:
      kubernetesNodeName: worker-node-3
  - role: worker
    labels:
      kubernetesNodeName: worker-node-4