# Example Group configuration for k3d testing environment
# This demonstrates a basic autoscaling group setup for development

apiVersion: infra.homecluster.dev/v1alpha1
kind: Group
metadata:
  name: k3d-workers
  namespace: homelab-autoscaler-system
spec:
  # Maximum number of nodes in this group
  maxSize: 3
  
  # Scale down when utilization is below 50%
  scaleDownUtilizationThreshold: 0.5
  
  # Wait 2 minutes before scaling down unneeded nodes
  scaleDownUnneededTime: "2m"
  
  # Wait 1 minute before scaling down unready nodes
  scaleDownUnreadyTime: "1m"
  
  # Maximum time to wait for a node to be provisioned
  maxNodeProvisionTime: "2m"
  
  # Ignore DaemonSet pods when calculating utilization
  ignoreDaemonSetsUtilization: true
  
  # Allow partial scaling (not just 0 or max)
  zeroOrMaxNodeScaling: false
  
  # GPU utilization threshold for scale down (if applicable)
  scaleDownGpuUtilizationThreshold: "30"