name: K3d Cluster Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      
      - name: Create cluster
        run: |
          chmod +x create-cluster.sh
          ./examples/k3d/create-cluster.sh
      
      - name: Run tests
        run: |
          kubectl get nodes
          # Your tests here
      
      - name: Delete cluster
        if: always()
        run: |
          chmod +x delete-cluster.sh
          ./examples/k3d/delete-cluster.sh
